# Generated by Django 5.0.3 on 2024-03-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0002_foodcat_alter_ipaddress1_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignwaiters',
            fields=[
                ('table_id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('emp_id', models.CharField(max_length=225)),
                ('emp_name', models.CharField(max_length=225)),
                ('asign_date', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('emp_id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('catImage', models.ImageField(upload_to='employee')),
                ('emp_name', models.CharField(max_length=225)),
                ('Birth', models.DateField(max_length=225)),
                ('NIC', models.CharField(max_length=225, unique=True)),
                ('address', models.CharField(max_length=225)),
                ('drl', models.CharField(max_length=225, null=True, unique=True)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225, null=True)),
                ('role', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='fooditem',
            fields=[
                ('food_id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('foodImage', models.ImageField(upload_to='food')),
                ('name', models.CharField(max_length=100)),
                ('catagories', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('short_description', models.TextField(max_length=225)),
                ('status', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='offers',
            fields=[
                ('offer_number', models.IntegerField(max_length=225, primary_key=True, serialize=False)),
                ('food_id', models.CharField(max_length=225)),
                ('food_name', models.CharField(max_length=225)),
                ('started_date', models.DateField(max_length=225)),
                ('end_date', models.DateField(max_length=225)),
                ('status', models.IntegerField(max_length=100)),
            ],
        ),
    ]
