# Generated by Django 5.0.3 on 2024-03-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0003_asignwaiters_employee_fooditem_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offer_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offers',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tables',
            name='times',
            field=models.IntegerField(null=True),
        ),
    ]
