# Generated by Django 5.0.3 on 2024-03-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0004_alter_fooditem_status_alter_offers_offer_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='waitermessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=225)),
                ('table_id', models.CharField(max_length=225)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
