# Generated by Django 5.0.3 on 2024-03-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0005_waitermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitermessage',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
