# Generated by Django 5.0.3 on 2024-03-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0006_waitermessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignwaiters',
            name='asign_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
