# Generated by Django 5.0.3 on 2024-03-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0008_alter_foodcat_number_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='assigncat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(max_length=225)),
                ('food_id', models.CharField(max_length=225)),
                ('name', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='price',
            field=models.CharField(default=2200, max_length=100),
            preserve_default=False,
        ),
    ]
