# Generated by Django 5.0.3 on 2024-03-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0009_assigncat_fooditem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='offImage',
            field=models.ImageField(null=True, upload_to='food'),
        ),
    ]
