# Generated by Django 5.0.3 on 2024-03-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0010_offers_offimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='offer_des',
            field=models.TextField(default='Create your personal my Social Security account today. A free and secure my …'),
            preserve_default=False,
        ),
    ]
