# Generated by Django 5.0.3 on 2024-03-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0011_offers_offer_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.CharField(max_length=225)),
                ('quantity', models.IntegerField(max_length=225)),
                ('order_des', models.TextField()),
                ('price', models.IntegerField(max_length=225)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
