# Generated by Django 5.0.3 on 2024-03-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0012_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.CharField(default=123, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='table_id',
            field=models.CharField(default=123, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(default='111', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipaddress1',
            name='user_id',
            field=models.CharField(default=1212, max_length=225, unique=True),
            preserve_default=False,
        ),
    ]
