# Generated by Django 5.0.3 on 2024-03-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0013_cart_order_id_cart_table_id_cart_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(max_length=225)),
                ('table_id', models.CharField(max_length=225)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=225)),
                ('pay_status', models.IntegerField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
            ],
        ),
    ]
