# Generated by Django 5.0.3 on 2024-04-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0016_alter_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_des',
            field=models.TextField(null=True),
        ),
    ]
