# Generated by Django 5.0.3 on 2024-04-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0017_alter_cart_order_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='food_name',
            field=models.CharField(default=2, max_length=225),
            preserve_default=False,
        ),
    ]
