# Generated by Django 5.0.3 on 2024-04-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0018_cart_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
