# Generated by Django 5.0.3 on 2024-04-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0019_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='value',
            field=models.CharField(default=1234, max_length=225),
            preserve_default=False,
        ),
    ]
