# Generated by Django 5.0.3 on 2024-04-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0020_order_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.IntegerField(null=True),
        ),
    ]
