# Generated by Django 5.0.3 on 2024-04-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0021_alter_order_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=225),
        ),
    ]
