# Generated by Django 5.0.3 on 2024-04-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0023_alter_fooditem_foodimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
