# Generated by Django 5.0.3 on 2024-04-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0024_tables_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tables',
            name='times',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
