# Generated by Django 5.0.3 on 2024-04-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0025_alter_tables_status_alter_tables_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='Table_catogary',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tables',
            name='max_member',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tables',
            name='table_number',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
