# Generated by Django 5.0.3 on 2024-04-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0026_alter_tables_table_catogary_alter_tables_max_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('order_id', models.CharField(max_length=225)),
                ('Uname', models.CharField(max_length=225)),
                ('moblie', models.CharField(max_length=225)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tables',
            name='qr_codes',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
