# Generated by Django 5.0.3 on 2024-04-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0027_tusers_alter_tables_qr_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress1',
            name='Time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipaddress1',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
