# Generated by Django 5.0.3 on 2024-04-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0028_alter_ipaddress1_time_alter_ipaddress1_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='action_status',
            field=models.IntegerField(null=True),
        ),
    ]
