# Generated by Django 5.0.3 on 2024-04-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0029_order_action_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_id',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
