# Generated by Django 5.0.3 on 2024-04-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0030_alter_order_table_id_alter_order_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='action_status',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
