# Generated by Django 5.0.3 on 2024-04-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0032_ipaddress1_name_ipaddress1_phone_order_chef_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='drl',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
