# Generated by Django 5.0.3 on 2024-04-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0033_alter_employee_drl'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcat',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodcat',
            name='add_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
