# Generated by Django 5.0.3 on 2024-04-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0035_alter_foodcat_catimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='catagories',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='catagory',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
