# Generated by Django 5.0.3 on 2024-04-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0036_remove_fooditem_catagories_fooditem_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='waiterAssignHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=225)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='asignwaiters',
            name='emp_status',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignwaiters',
            name='temp_id',
            field=models.CharField(default='12', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignwaiters',
            name='temp_name',
            field=models.CharField(default=1234, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignwaiters',
            name='temp_status',
            field=models.CharField(default=2212, max_length=225),
            preserve_default=False,
        ),
    ]
