# Generated by Django 5.0.3 on 2024-04-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0039_remove_posorder_id_posorder_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='POS_id',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
