# Generated by Django 5.0.3 on 2024-04-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0040_order_pos_id_order_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='POScart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=225)),
                ('food_id', models.CharField(max_length=225)),
                ('food_name', models.CharField(max_length=225)),
                ('order_id', models.CharField(max_length=225)),
                ('quantity', models.IntegerField()),
                ('order_des', models.TextField(null=True)),
                ('price', models.IntegerField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
