# Generated by Django 5.0.3 on 2024-04-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0044_alter_asignwaiters_temp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignwaiters',
            name='emp_id',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='asignwaiters',
            name='emp_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='asignwaiters',
            name='emp_status',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
