# Generated by Django 5.0.3 on 2024-04-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0045_alter_asignwaiters_emp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignwaiters',
            name='table_number',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
