# Generated by Django 5.0.3 on 2024-04-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0046_asignwaiters_table_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_uname', models.CharField(max_length=225)),
                ('Admin_password', models.CharField(max_length=225)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
