# Generated by Django 5.0.3 on 2024-04-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0047_admin_employee_password_employee_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='offer_des',
        ),
        migrations.AddField(
            model_name='offers',
            name='off_condition',
            field=models.CharField(default='sss', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers',
            name='off_topic',
            field=models.CharField(default='wwww', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers',
            name='offer',
            field=models.CharField(default='ww', max_length=225),
            preserve_default=False,
        ),
    ]
