# Generated by Django 5.0.3 on 2024-04-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0048_remove_offers_offer_des_offers_off_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
        migrations.AlterField(
            model_name='offers',
            name='offImage',
            field=models.ImageField(null=True, upload_to='promotion'),
        ),
    ]
