# Generated by Django 5.0.3 on 2024-04-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0049_remove_employee_username_alter_offers_offimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Birth',
            field=models.DateField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='catImage',
            field=models.ImageField(null=True, upload_to='employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
