# Generated by Django 5.0.3 on 2024-04-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0050_alter_employee_birth_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='POS_id',
            new_name='emp_id',
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
