# Generated by Django 5.0.3 on 2024-04-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0052_ipaddress1_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress1',
            name='emp_id',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
