# Generated by Django 5.0.3 on 2024-04-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0053_ipaddress1_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='cal',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
