# Generated by Django 5.0.3 on 2024-04-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0054_tables_cal'),
    ]

    operations = [
        migrations.CreateModel(
            name='topfooditem',
            fields=[
                ('food_id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('foodImage', models.ImageField(null=True, upload_to='food')),
                ('name', models.CharField(max_length=100)),
                ('catagory', models.CharField(max_length=225, null=True)),
                ('description', models.TextField()),
                ('short_description', models.TextField(max_length=225)),
                ('price', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='tables',
            name='times',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
